# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yROWWHFFQtjmjmT4rd0kjYL2kTqaPZQH
"""

pip install PyPDF2

from PyPDF2 import PdfReader

def extract_text_from_pdf(file_path):
    reader = PdfReader(file_path)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text

raw_text = extract_text_from_pdf("financial risk.pdf")

from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = text_splitter.split_text(raw_text)

print(f"Generated {len(chunks)} chunks.")

pip install openai

pip install langchain

!pip install -U langchain-community

!pip install tiktoken

from langchain.embeddings.openai import OpenAIEmbeddings

# Initialize OpenAI Embeddings
embeddings = OpenAIEmbeddings(openai_api_key="your_openai_api_key")
embedded_chunks = [embeddings.embed_query(chunk) for chunk in chunks]